# Meety: colour scheme "green"
cli:
  styles:
    matching_query:
      color: white
      background: on_green
      attrs: ["bold"]
    matching_preference:
      #color: white
      #background: on_green
      attrs: ["bold"]
    #others:
      #color: white            # default: None
      #background: on_green    # default: None
      #attrs: ["bold"]         # default: []

gui:
  styles:
    matching_query:
      size: 18
      color: "#06A446"
      background: "#eee"
      attrs: ["bold"]
      selected: "#ddd"
    matching_preference:
      size: 18
      color: "#444"
      background: "#eee"
      attrs: ["bold"]
      selected: "#ddd"
    others:
      size: 18
      color: "#888"
      background: "#eee"
      attrs: ["bold"]
      selected: "#ddd"
    info:
      show: yes
      size: 14
      color: "#888"
      attrs: []
      selected: "#ddd"
